USE [master]
GO

/****** Object:  Database [IFXDataBase]    Script Date: 26/03/2021 08:23:00 a. m. ******/
CREATE DATABASE [IFXDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IFXDataBase')
 LOG ON 
( NAME = N'IFXDataBase_log')
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IFXDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IFXDataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IFXDataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IFXDataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IFXDataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IFXDataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [IFXDataBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IFXDataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IFXDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IFXDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IFXDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IFXDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IFXDataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IFXDataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IFXDataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IFXDataBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IFXDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IFXDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IFXDataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IFXDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IFXDataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IFXDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IFXDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IFXDataBase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IFXDataBase] SET  MULTI_USER 
GO

ALTER DATABASE [IFXDataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IFXDataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IFXDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IFXDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IFXDataBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IFXDataBase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [IFXDataBase] SET  READ_WRITE 
GO


